extends: default

rules:
  line-length:
    max: 120

    level: warning
  indentation:
    spaces: 2
    indent-sequences: consistent
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  document-start: disable
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
  trailing-spaces: enable
  new-line-at-end-of-file: enable
  commas:
    max-spaces-before: 0
    max-spaces-after: 1