---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtiddsping-pub
  namespace: rti-examples
  labels:
    app: rtiddsping-pub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtiddsping-pub
  template:
    metadata:
      labels:
        app: rtiddsping-pub
    spec:
      containers:
        - name: rtiddsping-pub
          image: rticom/dds-ping:7.7.0
          args: ["-publisher", "-domainId", "10", "-verbosity", "1"]
