---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtiddsping-sub
  labels:
    app: rtiddsping-sub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtiddsping-sub
  template:
    metadata:
      labels:
        app: rtiddsping-sub
    spec:
      containers:
        - name: rtiddsping-sub
          image: rticom/dds-ping:7.3.0-EAR
          args: ["-subscriber", "-domainId", "10" ,"-verbosity", "2"]
      imagePullSecrets:
        - name: regcred
