---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtiddsping
  labels:
    app: rtiddsping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtiddsping
  template:
    metadata:
      labels:
        app: rtiddsping
    spec:
      containers:
        - name: rtiddsping-pub
          image: rticom/dds-ping:7.3.0-EAR
          args: ["-publisher", "-domainId", "10" ,"-verbosity", "2", "-transport", "3"]
          env:
            - name: NDDS_DISCOVERY_PEERS
              value: "shmem://,rtps@udpv4://rti-clouddiscoveryservice:7400"
        - name: rtiddsping-sub
          image: rticom/dds-ping:7.3.0-EAR
          args: ["-subscriber", "-domainId", "10" ,"-verbosity", "2", "-transport", "2"]
          env:
            - name: NDDS_DISCOVERY_PEERS
              value: "shmem://"
      imagePullSecrets:
        - name: regcred
