apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rticlouddiscoveryservice.yaml
  - rtiddsping_cds_sub.yaml
  - rtiroutingservice.yaml
  - rtiroutingservice_loadbalancer.yaml
