---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "rtiperftest-pub"
  labels:
    app: "rtiperftest-pub"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "rtiperftest-pub"
  template:
    metadata:
      labels:
        app: "rtiperftest-pub"
    spec:
      containers:
      - name: "rtiperftest-pub"
        image: "rticom/perftest:7.3.0"
        args: ["-pub"]
        env:
          - name: NDDS_DISCOVERY_PEERS
            value: rtps@udpv4://rti-clouddiscoveryservice:7400
        volumeMounts:
          - name: license-volume
            mountPath: /opt/rti.com/rti_connext_dds-7.3.0/rti_license.dat
            subPath: rti_license.dat
      volumes:
        - name: license-volume
          configMap:
            name: rti-license
