---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "rtiperftest-pub"
  namespace: "default"
  labels:
    app: "rtiperftest-pub"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "rtiperftest-pub"
  template:
    metadata:
      labels:
        app: "rtiperftest-pub"
    spec:
      containers:
      - name: "rtiperftest-pub"
        image: "rticom/perftest:v4.1"
        env:
          - name: "perftest_args"
            #value: "-pub -bestEffort -noPrint -latencyCount 1 -scan 32:64:128:256:512:1024:2048:4096:8192:16384:32768:63000 -latencyTest -executionTime 100"
            value: "-pub -noPrint -latencyCount 1 -scan 32:64:128:256:512:1024:2048:4096:8192:16384:32768:63000 -latencyTest -executionTime 100"
          - name: NDDS_DISCOVERY_PEERS
            value: rtps@rti-clouddiscoveryservice:7400
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        perftest_type: pub
