---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "rtiperftest-sub"
  labels:
    app: "rtiperftest-sub"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "rtiperftest-sub"
  template:
    metadata:
      labels:
        app: "rtiperftest-sub"
    spec:
      containers:
      - name: "rtiperftest-sub"
        image: "rticom/perftest:7.3.0"
        env:
        - name: "perftest_args"
          value: "-sub -noPrint"
          #value: "-sub -noPrint -bestEffort"
        - name: NDDS_DISCOVERY_PEERS
          value: rtps@rti-clouddiscoveryservice:7400
        volumeMounts:
          - name: license-volume
            mountPath: /opt/rti.com/rti_connext_dds-7.3.0/rti_license.dat
            subPath: rti_license.dat
      volumes:
        - name: license-volume
          configMap:
            name: rti-license

