apiVersion: v1
kind: Pod
metadata:
  name: secure-pub
  namespace: sandbox
spec:
  containers:
  - name: secure-pub
    image: secure_dds
    command: [ "/bin/bash", "-c", "--", "while true; do sleep 30; done;" ]
    imagePullPolicy: Never
    volumeMounts:
    # - name: governance
    #   mountPath: "/etc/secret/governance"
    #   readOnly: true
    - name: identity-ca
      mountPath: "/etc/secret/identity-ca"
      readOnly: true
    - name: identity-certificate
      mountPath: "/etc/secret/identity-certificate"
      readOnly: true
    # - name:  permissions-ca
    #   mountPath: "/etc/secret/permissions-ca"
    #   readOnly: true
    # - name:  permissions
    #   mountPath: "/etc/secret/permissions"
    #   readOnly: true
    - name:  private-key
      mountPath: "/etc/secret/private-key"
      readOnly: true
    - name:  pmi-signed
      mountPath: "/etc/secret/pmi-signed"
      readOnly: true
  volumes:
  # - name: governance
  #   secret:
  #     secretName: governance-secret
  - name: identity-ca
    secret:
      secretName: ca-root-secret
      items:
      - key: ca.crt
        path: ca/ca.crt
  - name: identity-certificate
    secret:
      secretName: alice-crt-secret
      items:
      - key: tls.crt
        path: alice-key/tls.crt
  # - name: permissions-ca
  #   secret:
  #     secretName: permissions-ca
  # - name: permissions
  #   secret:
  #     secretName: permissions-secret
  - name: private-key
    secret:
      secretName: alice-crt-secret
      items:
      - key: tls.key
        path: alice-key/tls.key   
  - name: pmi-signed
    secret:
      secretName: pmi-signed
  
---
apiVersion: v1
kind: Pod
metadata:
  name: secure-sub
  namespace: sandbox
spec:
  containers:
  - name: secure-sub
    image: secure_dds
    command: [ "/bin/bash", "-c", "--", "while true; do sleep 30; done;" ]
    imagePullPolicy: Never
    volumeMounts:
    # - name: governance
    #   mountPath: "/etc/secret/governance"
    #   readOnly: true
    - name: identity-ca
      mountPath: "/etc/secret/identity-ca"
      readOnly: true
    - name: identity-certificate
      mountPath: "/etc/secret/identity-certificate"
      readOnly: true
    # - name:  permissions-ca
    #   mountPath: "/etc/secret/permissions-ca"
    #   readOnly: true
    # - name:  permissions
    #   mountPath: "/etc/secret/permissions"
    #   readOnly: true
    - name:  private-key
      mountPath: "/etc/secret/private-key"
      readOnly: true

    - name:  pmi-signed
      mountPath: "/etc/secret/pmi-signed"
      readOnly: true
  volumes:
  # - name: governance
  #   secret:
  #     secretName: governance-secret
  - name: identity-ca
    secret:
      secretName: ca-root-secret
      items:
      - key: ca.crt
        path: ca/ca.crt
  - name: identity-certificate
    secret:
      secretName: alice-crt-secret
      items:
      - key: tls.crt
        path: alice-key/tls.crt
  # - name: permissions-ca
  #   secret:
  #     secretName: permissions-ca
  # - name: permissions
  #   secret:
  #     secretName: permissions-secret
  - name: private-key
    secret:
      secretName: alice-crt-secret
      items:
      - key: tls.key
        path: alice-key/tls.key
  - name: pmi-signed
    secret:
      secretName: pmi-signed

--- # Pod 2
# apiVersion: v1
# kind: Pod
# metadata:
#   name: mypod-2
#   namespace: sandbox
# spec:
#   containers:
#   - name: mypod-2
#     image: ubuntu
#     command: [ "/bin/bash", "-c", "--", "while true; do sleep 30; done;" ]
#     volumeMounts:
#     - name: foo
#       mountPath: "/etc/foo"
#       readOnly: true
#   volumes:
#   - name: foo
#     secret:
#       secretName: root-secret-2