apiVersion: v1
kind: Service
metadata:
  name: rs-rwt-0
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: rs-rwt-0
  ports:
    - nodePort: 30007
      protocol: UDP
      port: 7400
