apiVersion: v1
kind: Service
metadata:
  name: rs-rwt
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  ports:
  - port: 7400
    targetPort: 7400
    protocol: UDP
  selector:
    app: rti-routingservice
