apiVersion: v1
kind: Service
metadata:
  name: rti-routingservice
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: stickiness.enabled=true,stickiness.type=source_ip
spec:
  type: LoadBalancer
  ports:
  - port: 7400
    targetPort: 7400
    protocol: UDP
  selector:
    app: rti-routingservice
