apiVersion: apps/v1
kind: Deployment	
metadata:
  name: rti-routingservice
spec:
  selector:
    matchLabels:
      app: rti-routingservice
  replicas: 2
  template:
    metadata:
      labels:
        app: rti-routingservice
    spec:
      containers:
      - name: rti-routingservice
        image: kyoungho/rti-routingservice:6.1.1
        ports:
        - containerPort: 7400
          protocol: UDP
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.xml
          subPath: config.xml
        - name: license-volume
          mountPath: /app/license
        env:
        - name: ARGS
          value: "-cfgFile ./config.xml -cfgName RS-RWT -verbosity 5"
        - name: PUBLIC_IP # value for public ip address
          value: "a7a5c4bd86dcb49ffb449cbfcc8fe157-09daea9f71b38803.elb.us-east-2.amazonaws.com"
        - name: PUBLIC_PORT # value for public port
          value: "7400"
        - name: HOST_PORT # value for host port 
          value: "7400"
        - name: WAN_DOMAIN # value for WAN domain ID
          value: "100"
        - name: LAN_DOMAIN # value for LAN domain ID
          value: "10"
      imagePullSecrets:
        - name: regcred
      volumes: 
        - name: config-volume
          configMap:
            name: routingservice-rwt
        - name: license-volume
          configMap:
            name: rti-license
---
apiVersion: v1
kind: Service
metadata:
  name: rs-rwt
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  ports:
  - port: 7400
    targetPort: 7400
    protocol: UDP
  selector:
    app: rti-routingservice
