apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rti-cds
spec:
  selector:
    matchLabels:
      app: rti-cds
  serviceName: rti-cds-hs
  replicas: 2
  template:
    metadata:
      labels:
        app: rti-cds
    spec:
      containers:
        - name: rti-clouddiscoveryservice
          image: rticom/cloud-discovery-service:7.5.0.1
          volumeMounts:
            - name: license-volume
              mountPath: /opt/rti.com/rti_connext_dds-7.5.0/rti_license.dat
              subPath: rti_license.dat
          ports:
            - containerPort: 7400
              protocol: UDP
      volumes:
        - name: license-volume
          configMap:
            name: rti-license
---
apiVersion: v1
kind: Service
metadata:
  name: rti-cds-hs
  labels:
    app: rti-cds
spec:
  selector:
    app: rti-cds
  ports:
    - port: 7400
      protocol: UDP
  clusterIP: None
