apiVersion: v1
kind: Service
metadata:
  name: cds-nodeport
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: cds-rwt-0
  ports:
    - nodePort: 30007 # public port
      protocol: UDP
      port: 7400 # internal port
  externalTrafficPolicy: Local
