apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alice-cert
  namespace: sandbox
spec:
  secretName: alice-crt-secret
  commonName: alice-cert
  issuerRef:
    name: identity-ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
    group: cert-manager.io